### PR TITLE
Ready for azure pipelines integration tests

### PR DESCRIPTION
**Pull request by drageset**
- Specify to use `lds-server:1.0.9`, so future versions wont unexpectedly break the build.

- Delete the gsim-raml-schema project folder after we converted the raml to graphql and copied the graphql output into our own folder.

- I created a script to nuke ALL docker volumes on your host, and (re)start this service with a blank slate. NB: If you have anything running on your docker that relies on volumes, running this script **WILL** BREAK EVERYTHING.

- I created Dockerfiles for LDS and Postgres backends that contain everything they need (LDS image with GraphQL schema, Postgres with initialization script), so that they can be run in Azure more easily. I built and pushed the new images to my personal docker hub user. **_I have a feeling that is not the right way of doing it._** Maybe pushing them to GCR is more correct? How would I do that? I would probably need credentials.

- I created a script to re-build the custom images using a fresh GraphQL conversion of the schemas, and re-push them to docker hub with the "latest" tag. This script can be run every time there is an update to the gsim schemas.

- I wrote a `docker-compose` pointing to the new LDS and Postgres images, where they are currently located in my docker hub. This docker-compose should be possible to run in Azure Pipelines, at least as long as a [Docker Registry Service Connection](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#sep-docreg) to Docker Hub is properly set up. I have set that up, and uploaded the docker-compose file to "secure files". I also [added relevant DockerCompose tasks to the pipeline yaml](https://github.com/statisticsnorway/klass-subsets-api/pull/83) in a new branch of the klass-subsets-api repository, that I have not yet merged.

### CODE REVIEW

**Review by mmj-ssb — COMMENTED** [review]
So, it looks to me that you want to avoid having to run raml-to-graphql in you pipeline every time you want to setup a testrun, and I can certainly understand that. However, I think that you should either keep the resulting graphqlschema somewhere (instead of creating a new lds docker image) og simply run raml-to-graphql in the pipeline every time anyways. Personally I would prefer it if raml-to-graphql was run every time because this is a part of the LDS ecosystem anyways. The way you have done it now you would have to maintain olved/lds-with.graphql and olved/pg-for-lds which might sound like a small and unintrusive job in the beginning, but you would have to automate that aswell or else it is going to be more cumbersome than just running raml-to-graphql in the klass-subsets pipeline. Also, in the pipeline you should use the in-memory version of LDS and should not need to startup a Postgres Docker container.

**Comment by drageset** [comment]
Thanks for the feedback! I've now found a way of storing the SQL init and graphql schema in AP, and using them in the pipeline.

I will now look into how to build the graphql schema in the pipeline as you suggest. I think it is the best solution, but it's also a bit harder.

I agree that we don't strictly _**need**_ to use a postgres instance for the integration test in the pipeline, but isn't it best to do it still? It's a good thing to be sure that things work with the exact configuration we are using in staging/prod, to avoid potential "works-on-my-machine" gotcha's. What are the reasons _not_ to use Postgres? Extra resource usage? (I think its not that much)

**Comment by mmj-ssb** [comment]
> Thanks for the feedback @mmj-ssb ! I've now found a way of storing the SQL init and graphql schema in AP, and using them in the pipeline.

Nice!
> I will now look into how to build the graphql schema in the pipeline as you suggest. I think it is the best solution, but it's also a bit harder.

Yep, it sure is.

> I agree that we don't strictly _**need**_ to use a postgres instance for the integration test in the pipeline, but isn't it best to do it still? It's a good thing to be sure that things work with the exact configuration we are using in staging/prod, to avoid potential "works-on-my-machine" gotcha's. What are the reasons _not_ to use Postgres? Extra resource usage? (I think its not that much)

Well, yes and no, the only thing you are (and should be) testing in your pipeline is klass-subsets integration with the LDS api, not its underlying database. However you are correct in the fact that you actually get to test against an LDS configured with a Postgres spesifically. Which might be useful. I have no strong opinions for or against. The only thing I was thinking of with using the in-memory version of LDS is that the startup time for it vs. LDS and Postgres Docker containers I believe will be significantly shorter (I may be wrong). It might become a nuisence if the pipeline lasts many minutes each time. But you can start with a Postgres instance and see how it goes.

**Comment by drageset** [comment]
> 
> 
> > Thanks for the feedback @mmj-ssb ! I've now found a way of storing the SQL init and graphql schema in AP, and using them in the pipeline.
> 
> Nice!
> 
> > I will now look into how to build the graphql schema in the pipeline as you suggest. I think it is the best solution, but it's also a bit harder.
> 
> Yep, it sure is.
> 
> > I agree that we don't strictly _**need**_ to use a postgres instance for the integration test in the pipeline, but isn't it best to do it still? It's a good thing to be sure that things work with the exact configuration we are using in staging/prod, to avoid potential "works-on-my-machine" gotcha's. What are the reasons _not_ to use Postgres? Extra resource usage? (I think its not that much)
> 
> LDS and Postgres Docker containers I believe will be significantly shorter (I may be wrong). It might become a nuisence if the pipeline lasts many minutes each time. But you can start with a Postgres instance and see how it goes.

Thanks for the tip, good to know! If it takes too long and I want to make it faster, I know where to start looking.

**Review by mmj-ssb — APPROVED** [review]

**Pull request merged**
